services:
  api:
    build:
      context: ../aventureo-back
      dockerfile: ../aventureo-back/Dockerfile
    ports:
      - "8080:8080"
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api