name: Docker Image CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  EKS_CLUSTER_NAME: aventureo-tfg
  AWS_REGION: us-east-1
jobs:

  build:
  
    name: Deployment
    runs-on: ubuntu-latest

    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker Metadata for Image
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: a27300/aventureo-front
        flavor: |
          latest=false
        tags: |
          type=raw,value=06

    - name: Build and Push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v5
      with:
       push: true
       tags: ${{ steps.docker_meta.outputs.tags }}
       labels: ${{ steps.docker_meta.outputs.labels }}
       cache-from: type=gha
       cache-to: type=gha,mode=max
       platforms: linux/amd64
    
    - name: Check out code
      uses: actions/checkout@v2     
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
        kubectl apply -f manifests/deploy-front.yaml
        kubectl apply -f manifests/svc-front.yaml
